GET http://localhost:8080/api/v1/dashboard/drivers
Content-Type: application/json


###
POST http://localhost:8080/api/v1/dashboard/driver
Content-Type: application/json

{
  "fullName": "Marco",
  "email": "andreose.marco93@gmail.com",
  "phone": "3333333333",
  "licenseNumber": "ABC123456"
}

###
POST http://localhost:8090/api/v1/telemetry
Content-Type: application/json

{
  "driverUid": "c453b0e4-0304-4469-b343-4b5afd94c6cf",
  "lng": 39.651212,
  "lat": 136.651212,
  "recordedAt": "2026-03-21T23:01:10Z"
}


###
POST http://localhost:8090/api/v1/telemetry
Content-Type: application/json

{
  "driverUid": "c453b0e4-0304-4469-b343-4b5afd94c6cf",
  "lng": 39.651212,
  "lat": 136.651212,
  "recordedAt": "2026-03-24T10:16:36Z"
}



