spring:
  application:
    name: logistics-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:password}
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost       # service name in docker-compose
      port: 6379
      timeout: 10000
      password: yourpassword
  cache:
    type: redis
    redis:
      time-to-live: 300000   # 5 minutes in milliseconds
rabbitmq:
  exchange: telemtry.exchange
  queue: telemetry.queue
  routing-key: telemetry.#
  dlq: telemetry.dlq
server:
  port: 8080

